// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBJruwbsSTqDSyr-57llS9HR-BKIHRc0A',
    appId: '1:210962995780:web:49655e70034c173891ba11',
    messagingSenderId: '210962995780',
    projectId: 'maratha-matrimony-app',
    authDomain: 'maratha-matrimony-app.firebaseapp.com',
    storageBucket: 'maratha-matrimony-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFRyeTUIIxoeUs5IwcwLvJgEKR-yOpJnk',
    appId: '1:210962995780:android:fbfa81100fad3bfe91ba11',
    messagingSenderId: '210962995780',
    projectId: 'maratha-matrimony-app',
    storageBucket: 'maratha-matrimony-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCng5sUNSiZ6h3TaBvwARgl23ZKpLmpCo8',
    appId: '1:210962995780:ios:edb4020b280370bc91ba11',
    messagingSenderId: '210962995780',
    projectId: 'maratha-matrimony-app',
    storageBucket: 'maratha-matrimony-app.appspot.com',
    iosClientId: '210962995780-ic1c3n6k6qs08lhuq2kpmfe8fd5ousqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.marathaMatrimonyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCng5sUNSiZ6h3TaBvwARgl23ZKpLmpCo8',
    appId: '1:210962995780:ios:edb4020b280370bc91ba11',
    messagingSenderId: '210962995780',
    projectId: 'maratha-matrimony-app',
    storageBucket: 'maratha-matrimony-app.appspot.com',
    iosClientId: '210962995780-ic1c3n6k6qs08lhuq2kpmfe8fd5ousqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.marathaMatrimonyApp',
  );
}
